# Generated by Django 6.1.1 on 2026-10-02 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarroMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('CARRERA', 'Carrera/Bootcamp'), ('RELAMPAGO', 'Curso Relámpago')], default='CARRERA', max_length=20)),
                ('precio_original', models.DecimalField(decimal_places=0, max_digits=10)),
                ('descuento_porcentaje', models.PositiveIntegerField(default=0)),
                ('cupos_totales', models.PositiveIntegerField()),
                ('cupos_disponibles', models.PositiveIntegerField()),
                ('nivel', models.CharField(blank=True, max_length=50, null=True)),
                ('semanas_duracion', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_cursos', models.PositiveIntegerField(blank=True, null=True)),
                ('duracion_horas', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('duracion_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='core.area')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('costo_total', models.DecimalField(decimal_places=0, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_pagado', models.DecimalField(decimal_places=0, max_digits=10)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.curso')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('COORDINADOR', 'Coordinador')], default='ESTUDIANTE', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agregado_en', models.DateTimeField(auto_now_add=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.carromatricula')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
            ],
            options={
                'unique_together': {('carro', 'curso')},
            },
        ),
    ]
