# Generated by Django 6.1.1 on 2026-10-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Sube una imagen desde tu equipo', null=True, upload_to='cursos/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='O usa una URL de imagen', null=True),
        ),
    ]
