# Generated by Django 6.1.1 on 2026-10-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_curso_imagen_alter_curso_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='ultima_actividad',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('COORDINADOR', 'Coordinador'), ('ADMIN', 'Administrador Global')], default='ESTUDIANTE', max_length=20),
        ),
    ]
